github-repo: "https://github.com/spring-io/spring-asciidoctor-extensions.git"
github-repo-name: "spring-io/spring-asciidoctor-extensions"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
build-name: "spring-asciidoctor-extensions"
ci-image-name: "spring-asciidoctor-extensions-ci"
bintray-subject: "spring"
bintray-repo: "jars"
